spring:
  application:
    name: hmby
  datasource:
    url: jdbc:postgresql://localhost:5433/hmby
    username: postgres
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate.format_sql: true
  web:
    resources:
      static-locations: classpath:/dist/
  mvc:
    static-path-pattern: /web/**
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1024
        max-document-batch-size: 1000 # Optional: Maximum number of documents per batch
server:
  port: 8094
  
hmby:
  config:
    ffmpeg-path: /opt/homebrew/bin/ffmpeg
    ffprobe-path: /opt/homebrew/bin/ffprobe
    emby-server: http://localhost:8096
    volume-bind:
      - /Volumes/downloads/->/downloads/
      - /Volumes/Volume1/->/Volume1
      - /Volumes/Volume2/->/Volume2
    output-media-path: /Volumes/downloads/output
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.springframework.ai.chat.client.advisor: DEBUG