spring:
  application:
    name: hmby
  datasource:
    url: jdbc:postgresql://192.168.123.232:5432/hmby
    username: postgres
    password: dev
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#        hibernate.format_sql: true
  web:
    resources:
      static-locations: classpath:/dist/
  mvc:
    static-path-pattern: /web/**
server:
  port: 8094
  
hmby:
  config:
    output-media-path: /downloads/output
    volume-bind:
      - \\192.168.123.232\downloads\->/downloads/
      - \\192.168.123.232\Volume1\->/Volume1
      - \\192.168.123.232\Volume2\->/Volume2
#logging.level.org.hibernate.SQL: DEBUG
#logging.level.org.example.hmby.config: DEBUG
openai:
  base-url: http://localhost:1234/v1
  api-key: 1234
  model: qwen2.5-14b-instruct-1m-abliterated
  embedding-model: text-embedding-qwen3-embedding-0.6b