spring:
  application:
    name: hmby
  datasource:
    url: jdbc:postgresql://localhost:5432/hmby
    username: dev
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/dist/
  mvc:
    static-path-pattern: /web/**
  ai:
    mcp:
      client:
        connection-timeout: 60s
        type: ASYNC
        stdio:
          servers-configuration: classpath:mcp-servers.json
        toolcallback:
          enabled: true
server:
  port: 8094

hmby:
  config:
    ffmpeg-path: /opt/homebrew/bin/ffmpeg
    ffprobe-path: /opt/homebrew/bin/ffprobe
    emby-server: http://localhost:8096
    volume-bind:
      - /Volumes/downloads/->/downloads/
      - /Volumes/Volume1/->/Volume1
      - /Volumes/Volume2/->/Volume2
    output-media-path: /Volumes/downloads/output
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.springframework.ai.chat.client.advisor: DEBUG