spring:
  application:
    name: hmby
  datasource:
    url: jdbc:postgresql://192.168.123.232:5432/hmby
    username: postgres
    password: dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate.format_sql: true
  web:
    resources:
      static-locations: classpath:/dist/
  mvc:
    static-path-pattern: /web/**
server:
  port: 8094
  
hmby:
  config:
    ffmpeg-path: E:\ffmpeg\bin\ffmpeg
    ffprobe-path: E:\ffmpeg\bin\ffprobe
    emby-server: http://192.168.123.232:8096
    volume-bind: 
    - \\192.168.123.232\downloads\->/downloads/
    - \\192.168.123.232\Volume1\->/Volume1
    - \\192.168.123.232\Volume2\->/Volume2
    output-media-path: /downloads/output
logging:
  level:
    org.springframework.ai.openai: DEBUG
    org.example.hmby.config.EmbyFeignClientConfig: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.orm.jdbc.extract: TRACE